### ISSUE TITLE
Undergarden Portal Won't Open?

### ISSUE THREAD

**Issue by AllenSeitz** [Warhand/Limitless-rebirth-1.18.2#2]
**Describe the bug**
The Undergarden portal did not open when I used the Catalyst on the bottom of the portal frame.

**To Reproduce**
I built the Undergarden portal frame out of stone bricks like normal. (And definitely stone bricks, not infested stone bricks.) I then crafted a Catalyst and tried to use it on the inside of either lower brick blocks. The portal did not open.

**Expected behavior**
Portal opens.

**Screenshots**

**Modpack version:**
Public beta 4.

**Desktop (please complete the following information):**
Windows 10, launched from the official launcher.

**Additional context**
Single player.

**Comment by Warhand** [comment]
This is intended behavior, normal stone bricks have been removed as valid portal frame blocks for the Undergarden, leaving deepslate bricks as the intended frame.

I personally feel as though deepslate makes a bit more sense for a dimension like the undergarden, though I will certainly be making an effort to make that change a bit clearer.

I'll leave this issue open for now until I implement something that makes it clearer that this is intended.
