### ISSUE TITLE
Many DimDungeons Chets Empty

### ISSUE THREAD

**Issue by AllenSeitz** [Warhand/Limitless-rebirth-1.18.2#3]
**Describe the bug**
Many chests are empty or are rolling empty.

**To Reproduce**
1. Build a new DimDungeon.
2. Fly around in creative/spectator mode and inspect the chests. (/data get block [looking at])
3. Many chests are starting with no inventory or loot table. And it seems like the ones that "roll up" are empty.

**Expected behavior**
Always loot!

**Screenshots**

**Modpack version:**
Public Beta 4

**Comment by Warhand** [comment]
Issue fixed: https://github.com/Warhand/Limitless-rebirth-1.18.2/commit/d07ae360a585d88d7a4c8acf881fe58d269f9376
